version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_USER=
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3307:3306
    expose:
      - 3307
    volumes:
      - db:/var/lib/mysql
volumes:
  db: