version: '3'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    environment:
      - REDIS_HOST=myredis
    networks:
      - redis-network
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '9001:8001'
    networks:
      - redis-network
    volumes:
      - db:/data
networks:
  redis-network:
    driver: bridge

volumes:
  db: