version: '3'
services:
  redis:
    image: redislabs/redismod
    ports:
      - 6379:6379
    networks:
      - redis-network
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    networks:
      - redis-network
    volumes:
      - db:/db
networks:
  redis-network:
    driver: bridge

volumes:
  db: